name: Build site and upload to s3.joeyh.dev

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.21
    steps:
      - uses: actions/checkout@v3
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install  mdbook mdbook-katex
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with mdBook
        run: mdbook build

      - name: Minio Deploy
        env:
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc --output mc
          chmod +x mc
          ./mc alias set deploy https://s3.joeyh.dev $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
          ./mc mirror --remove --overwrite ./book deploy/notes && ./mc anonymous set download deploy/notes

